# Generated by Django 2.2.1 on 2019-09-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Designates whether this user's email is verified . ", verbose_name='email verified'),
        ),
    ]
