# Generated by Django 2.2.1 on 2019-09-01 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('line', models.CharField(blank=True, max_length=1, null=True)),
                ('main_data', models.CharField(max_length=2000)),
                ('main_data_display', models.CharField(blank=True, max_length=2500, null=True)),
                ('written_on', models.DateField(auto_now=True)),
                ('important', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='article/image/')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchTag',
            fields=[
                ('search_tag', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tag_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discord',
            fields=[
                ('discord_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=5000)),
                ('line', models.CharField(max_length=3000)),
                ('main_data', models.CharField(max_length=20000)),
                ('written_on', models.DateField(auto_now=True)),
                ('important', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discord', to=settings.AUTH_USER_MODEL)),
                ('nested_discord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_discord', to='reader__API.Discord')),
                ('related_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_discord', to='reader__API.Article')),
                ('search_tag', models.ManyToManyField(blank=True, related_name='tagged_discord', to='reader__API.SearchTag')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='search_tag',
            field=models.ManyToManyField(blank=True, related_name='tagged_articles', to='reader__API.SearchTag'),
        ),
    ]
