# Generated by Django 2.2.1 on 2019-09-01 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestSave',
            fields=[
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='savedArticle', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('main_data', models.CharField(max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='article/temp/')),
            ],
        ),
    ]
