# Generated by Django 2.2.1 on 2019-09-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=20)),
                ('email', models.EmailField(editable=False, max_length=254)),
                ('detail', models.CharField(editable=False, max_length=100)),
                ('is_user', models.BooleanField(default=False, editable=False)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
